name: Run Selenium Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      mode:
        description: "Test mode: all | changed | path | marker"
        required: true
        default: "changed"
      test_path:
        description: "Path to tests (if mode=path)"
        required: false
      test_marker:
        description: "Pytest marker (if mode=marker)"
        required: false

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libnss3 libgtk-3-0 libasound2t64
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Verify Chrome & Driver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run tests
        run: |
          python3 --version
          pip3 --version
          python3 -m pytest --version

          MODE="${{ github.event.inputs.mode }}"
          PATH_INPUT="${{ github.event.inputs.test_path }}"
          MARKER="${{ github.event.inputs.test_marker }}"

          echo "Mode: $MODE"
          echo "Test path: $PATH_INPUT"
          echo "Marker: $MARKER"

          if [[ "$MODE" == "all" ]]; then
            python3 -m pytest

          elif [[ "$MODE" == "changed" ]]; then
            # На пуше: берём изменённые тесты
            CHANGED_TESTS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'tests/.*\.py$' || true)
            echo "Changed test files: $CHANGED_TESTS"
            if [ -n "$CHANGED_TESTS" ]; then
              python3 -m pytest $CHANGED_TESTS
            else
              echo "No changed tests found."
            fi

          elif [[ "$MODE" == "path" ]]; then
            if [ -n "$PATH_INPUT" ]; then
              python3 -m pytest "$PATH_INPUT"
            else
              echo "Error: test_path is empty"
              exit 1
            fi

          elif [[ "$MODE" == "marker" ]]; then
            if [ -n "$MARKER" ]; then
              python3 -m pytest -m "$MARKER"
            else
              echo "Error: test_marker is empty"
              exit 1
            fi

          else
            echo "Invalid mode: $MODE"
            exit 1


